### ISSUE TITLE
Remove Google Analytics

### ISSUE THREAD

**Issue by poperigby** [os-js/os.js.org#12]
Would you be willing to remove the Google Analytics 'functionality' from this website? There are better alternatives if you _must_ keep tabs on users' activity.
If you must have an analytics system, might I suggest either:
 - Plausible: https://plausible.io (offers a 50% discount for FOSS projects)
 - Goatcounter: https://goatcounter.com
 - Matomo: https://matomo.org

 These solutions are all well-tested and open-source. This, of course, means they
 can be independently audited for privacy and security. Instead of using a proprietary
 nonfree system such as Google Analytics, perhaps we could work together to replace
 it with something slightly more ethical?

 Furthermore, the majority of privacy features in evergreen browsers *block* Google
 Analytics from being run. I can not say the same for solutions such as Plausible,
 which suggests they are trusted for their privacy by independent persons.

**Comment by andersevenrud** [comment]
I've already got a PR open for this in https://github.com/os-js/manual.os-js.org/pull/28 that I will implement here as well. I first tried Matomo, but so far it's been kind of a pain, so I'm looking at other alternatives.
